import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline">Hello world!</h1>

      <div className="flex flex-col">
        <div className="bg-green-300">1</div>
        <div className="bg-red-300">2</div>
        <div className="bg-blue-300">3</div>
      </div>
    </div>
  );
}
